export const QUESTIONS_LIST_REQUEST = "QUESTIONS_LIST_REQUEST"
export const QUESTIONS_LIST_SUCCESS = "QUESTIONS_LIST_SUCCESS"
export const QUESTIONS_LIST_FAIL = "QUESTIONS_LIST_FAIL"

export const QUESTIONS_ADD_REQUEST = "QUESTIONS_ADD_REQUEST"
export const QUESTIONS_ADD_SUCCESS = "QUESTIONS_ADD_SUCCESS"
export const QUESTIONS_ADD_FAIL = "QUESTIONS_ADD_FAIL"