export const QUESTIONS_LIST_REQUEST = "QUESTIONS_LIST_REQUEST"
export const QUESTIONS_LIST_SUCCESS = "QUESTIONS_LIST_SUCCESS"
export const QUESTIONS_LIST_FAIL = "QUESTIONS_LIST_FAIL"

export const QUESTIONS_ADD_REQUEST = "QUESTIONS_ADD_REQUEST"
export const QUESTIONS_ADD_SUCCESS = "QUESTIONS_ADD_SUCCESS"
export const QUESTIONS_ADD_FAIL = "QUESTIONS_ADD_FAIL"

export const QUESTIONS_DELETE_REQUEST = "QUESTIONS_DELETE_REQUEST"
export const QUESTIONS_DELETE_SUCCESS = "QUESTIONS_DELETE_SUCCESS"
export const QUESTIONS_DELETE_FAIL = "QUESTIONS_DELETE_FAIL"

export const QUESTIONS_EDIT_REQUEST = "QUESTIONS_EDIT_REQUEST"
export const QUESTIONS_EDIT_SUCCESS = "QUESTIONS_EDIT_SUCCESS"
export const QUESTIONS_EDIT_FAIL = "QUESTIONS_EDIT_FAIL"

export const QUESTIONS_ALL_REQUEST = "QUESTIONS_ALL_REQUEST"
export const QUESTIONS_ALL_SUCCESS = "QUESTIONS_ALL_SUCCESS"
export const QUESTIONS_ALL_FAIL = "QUESTIONS_ALL_FAIL"

export const QUESTIONS_REPLY_REQUEST = "QUESTIONS_REPLY_REQUEST"
export const QUESTIONS_REPLY_SUCCESS = "QUESTIONS_REPLY_SUCCESS"
export const QUESTIONS_REPLY_FAIL = "QUESTIONS_REPLY_FAIL"

export const QUESTIONS_SINGLE_REQUEST = "QUESTIONS_SINGLE_REQUEST"
export const QUESTIONS_SINGLE_SUCCESS = "QUESTIONS_SINGLE_SUCCESS"
export const QUESTIONS_SINGLE_FAIL = "QUESTIONS_SINGLE_FAIL"